# Generated by Django 4.2.3 on 2023-08-04 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('telefone', models.CharField(max_length=200, null=True)),
                ('data', models.CharField(max_length=200, null=True)),
                ('qtd_acompanhantes', models.IntegerField(null=True)),
                ('observacao', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, null=True)),
                ('imagem', models.CharField(max_length=200, null=True)),
                ('preco_cota', models.CharField(max_length=200, null=True)),
                ('qtd_clicks', models.IntegerField(null=True)),
                ('qtd_cotas_maxima', models.IntegerField(null=True)),
                ('preco_total', models.CharField(max_length=200, null=True)),
                ('vlr_preco_total', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('vlr_preco_cota', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('categoria', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_cota', models.IntegerField(null=True)),
                ('imagem', models.CharField(max_length=200, null=True)),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.produto')),
            ],
        ),
    ]
