# Generated by Django 4.2.3 on 2023-08-08 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoConfirmacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=200, null=True)),
                ('nome', models.CharField(max_length=200, null=True)),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.produto')),
            ],
        ),
    ]
