# Generated by Django 4.2.3 on 2023-08-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produto_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='chave',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
